# Graph recommendation

In [1]:
%load_ext kedro.extras.extensions.ipython

[09/06/22 13:58:18] INFO     Updated path to Kedro project: /home/michal/projects/gid-ml-framework    ]8;id=51794;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=958953;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#53\53]8;;\

[09/06/22 13:58:20] INFO     The 'mlflow_tracking_uri' key in mlflow.yml is relative     ]8;id=544941;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro_mlflow/config/kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=334186;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro_mlflow/config/kedro_mlflow_config.py#202\202]8;;\
                             ('server.mlflow_tracking_uri = mlruns'). It is converted to                           
                             a valid uri:                                                                          
                             'file:///home/michal/projects/gid-ml-framework/mlruns'                                

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=842447;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=427893;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/kedro/framework/context/context.py:344: UserWarning: Credentials                   
                             not found in your Kedro project config.                                               
                             No files found in ['/home/michal/projects/gid-ml-framework/conf/base',                
                             '/home/michal/projects/gid-ml-framework/conf/local'] matching the glob                
                             pattern(s): ['credentials*', 'credentials*/**', '**/credentials*']                    
                               warn(f"Credentials not found in your Kedro project                                  
                             config.\n{str(exc)}")                                                                 
                                                                                                                   

[09/06/22 13:58:22] WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=293465;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=976786;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/dgl/backend/pytorch/tensor.py:16: DeprecationWarning: distutils                    
                             Version classes are deprecated. Use packaging.version instead.                        
                               if LooseVersion(th.__version__) < LooseVersion("1.9.0"):                            
                                                                                                                   

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=877057;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=943059;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/dgl/backend/pytorch/tensor.py:340: DeprecationWarning: distutils                   
                             Version classes are deprecated. Use packaging.version instead.                        
                               if LooseVersion(th.__version__) >= LooseVersion("1.10.0"):                          
                                                                                                                   

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=458111;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=938672;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/dgl/dataloading/dataloader.py:32: DeprecationWarning: distutils                    
                             Version classes are deprecated. Use packaging.version instead.                        
                               PYTORCH_VER = LooseVersion(torch.__version__)                                       
                                                                                                                   

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=71023;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=511335;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/dgl/_dataloading/pytorch/dataloader.py:24: DeprecationWarning:                     
                             distutils Version classes are deprecated. Use packaging.version                       
                             instead.                                                                              
                               PYTORCH_VER = LooseVersion(th.__version__)                                          
                                                                                                                   

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=874041;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=770236;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/dgl/_dataloading/pytorch/dataloader.py:25: DeprecationWarning:                     
                             distutils Version classes are deprecated. Use packaging.version                       
                             instead.                                                                              
                               PYTORCH_16 = PYTORCH_VER >= LooseVersion("1.6.0")                                   
                                                                                                                   

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=958208;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=495465;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/dgl/_dataloading/pytorch/dataloader.py:26: DeprecationWarning:                     
                             distutils Version classes are deprecated. Use packaging.version                       
                             instead.                                                                              
                               PYTORCH_17 = PYTORCH_VER >= LooseVersion("1.7.0")                                   
                                                                                                                   

                    INFO     Kedro project GetInData ML Framework                                     ]8;id=61603;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=703977;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#78\78]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and 'pipelines'  ]8;id=369845;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=35623;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#79\79]8;;\

[09/06/22 13:58:23] WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=457163;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=124647;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/plotly/graph_objects/__init__.py:288: DeprecationWarning: distutils                
                             Version classes are deprecated. Use packaging.version instead.                        
                               if LooseVersion(ipywidgets.__version__) >= LooseVersion("7.0.0"):                   
                                                                                                                   

[09/06/22 13:58:24] INFO     Registered line magic 'run_viz'                                          ]8;id=171602;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=394776;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#85\85]8;;\

                    INFO     Registered line magic 'reload_kedro_mlflow'                              ]8;id=56297;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=579290;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#85\85]8;;\

In [2]:
%reload_kedro

                    INFO     No path argument was provided. Using:                                    ]8;id=360024;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=383132;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#55\55]8;;\
                             /home/michal/projects/gid-ml-framework                                                

[09/06/22 13:58:25] INFO     The 'mlflow_tracking_uri' key in mlflow.yml is relative     ]8;id=634191;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro_mlflow/config/kedro_mlflow_config.py\kedro_mlflow_config.py]8;;\:]8;id=68253;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro_mlflow/config/kedro_mlflow_config.py#202\202]8;;\
                             ('server.mlflow_tracking_uri = mlruns'). It is converted to                           
                             a valid uri:                                                                          
                             'file:///home/michal/projects/gid-ml-framework/mlruns'                                

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=382307;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=806149;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/kedro/framework/context/context.py:344: UserWarning: Credentials                   
                             not found in your Kedro project config.                                               
                             No files found in ['/home/michal/projects/gid-ml-framework/conf/base',                
                             '/home/michal/projects/gid-ml-framework/conf/local'] matching the glob                
                             pattern(s): ['credentials*', 'credentials*/**', '**/credentials*']                    
                               warn(f"Credentials not found in your Kedro project                                  
                             config.\n{str(exc)}")                                                                 
                                                                                                                   

                    INFO     Kedro project GetInData ML Framework                                     ]8;id=408887;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=829503;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#78\78]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and 'pipelines'  ]8;id=551714;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=761167;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#79\79]8;;\

                    INFO     Registered line magic 'run_viz'                                          ]8;id=526293;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=486455;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#85\85]8;;\

                    INFO     Registered line magic 'reload_kedro_mlflow'                              ]8;id=510515;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py\ipython.py]8;;\:]8;id=303632;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/extras/extensions/ipython.py#85\85]8;;\

In [4]:
from typing import Iterator, Tuple
import re

from kedro.extras.datasets.pandas import CSVDataSet
from kedro.io.core import get_filepath_str
import numpy as np
import pandas as pd
import dgl
from dgl.sampling import sample_neighbors, select_topk
from dgl import save_graphs
import torch

import gid_ml_framework.pipelines.santander_preprocessing.nodes
from gid_ml_framework.extras.datasets.chunks_dataset import (
 _concat_chunks,
)

pd.options.mode.chained_assignment = None
pd.set_option('expand_frame_repr', True)
pd.set_option("display.max_rows", 999)
pd.set_option('max_colwidth', 100)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.expand_frame_repr', False)

In [5]:
dataset = "santander"

In [6]:
transactions_graph_path = f"{dataset}.transactions_graph"
transactions_mapped_path = f"{dataset}_transactions_mapped"
users_mapping_path = f"{dataset}_users_mapping"
items_mapping_path = f"{dataset}_items_mapping"
neg_transactions_path = f"{dataset}_dgsr_negative_transactions_samples"

In [7]:
transactions_mapped = _concat_chunks(context.catalog.load(transactions_mapped_path))
neg_transactions = _concat_chunks(context.catalog.load(neg_transactions_path))

[09/06/22 13:59:00] WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=164001;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=859936;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/kedro/framework/context/context.py:344: UserWarning: Credentials                   
                             not found in your Kedro project config.                                               
                             No files found in ['/home/michal/projects/gid-ml-framework/conf/base',                
                             '/home/michal/projects/gid-ml-framework/conf/local'] matching the glob                
                             pattern(s): ['credentials*', 'credentials*/**', '**/credentials*']                    
                               warn(f"Credentials not found in your Kedro project                                  
                             config.\n{str(exc)}")                                                                 
                                                                                                                   

                    INFO     Loading data from 'santander_transactions_mapped' (CSVDataSet)...  ]8;id=258285;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=965257;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/io/data_catalog.py#343\343]8;;\

                    WARNING  /home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packag ]8;id=355249;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py\warnings.py]8;;\:]8;id=479868;file:///home/michal/.pyenv/versions/3.8.12/lib/python3.8/warnings.py#109\109]8;;\
                             es/kedro/framework/context/context.py:344: UserWarning: Credentials                   
                             not found in your Kedro project config.                                               
                             No files found in ['/home/michal/projects/gid-ml-framework/conf/base',                
                             '/home/michal/projects/gid-ml-framework/conf/local'] matching the glob                
                             pattern(s): ['credentials*', 'credentials*/**', '**/credentials*']                    
                               warn(f"Credentials not found in your Kedro project                                  
                             config.\n{str(exc)}")                                                                 
                                                                                                                   

                    INFO     Loading data from 'santander_dgsr_negative_transactions_samples'   ]8;id=824689;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=263683;file:///home/michal/projects/gid-ml-framework/.venv/lib/python3.8/site-packages/kedro/io/data_catalog.py#343\343]8;;\
                             (CSVDataSet)...                                                                       

In [12]:
neg_transactions

item_id 
 
 
 
 
 0 
 [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 19 21 22] 
 
 
 1 
 [ 0 1 2 3 4 5 6 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 2 
 [ 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 3 
 [ 0 1 2 4 5 6 7 8 9 10 11 13 14 15 16 17 18 19 20 21 22] 
 
 
 4 
 [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 16 17 18 19 20 21 22] 
 
 
 ... 
 ... 
 
 
 20582 
 [ 0 1 2 3 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 20583 
 [ 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 20584 
 [ 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 20585 
 [ 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 20586 
 [ 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22] 
 
 
 
 20587 rows × 1 columns